"""INDEX.md: the table of contents for the whole Knowledge Base."""

from __future__ import annotations

from generator import markdown
from generator.models import Document

_DESCRIPTION = "Table of contents for the Knowledge Base."


def render(documents: tuple[Document, ...]) -> Document:
    parts = [markdown.heading("Knowledge Base Index", 1)]
    parts.append(
        markdown.paragraph(
            "Generated by Save your Tokens. Start with [AI_CONTEXT.md](AI_CONTEXT.md)."
        )
    )

    rows = [
        [f"[{document.filename}]({document.filename})", document.description]
        for document in documents
    ]
    parts.append(markdown.table(["Document", "Description"], rows))

    body = "\n".join(parts)
    return Document("INDEX.md", "Index", _DESCRIPTION, body)
